import "./globals.css";
import Navigation from "@/components/Navigation";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Blog de Doug",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="es"
      className="bg-neutral-950 text-white m-5 sm:mx-auto sm:max-w-2xl"
    >
      <body className="flex flex-col md:mt-16">
        <Navigation />
        <hr className="my-6 h-px bg-neutral-600 border-0" />
        <main>{children}</main>
        <Analytics />
      </body>
    </html>
  );
}
