import "./globals.css";
import Navigation from "@/components/Navigation";

export const metadata = {
  title: "Doug's tech blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className="bg-neutral-950 font-montserrat text-white">
      <body className="flex flex-col mt-4 mx-4 max-w-4xl sm:flex-row">
        <Navigation />
        <main className="flex flex-col mt-4 px-2">{children}</main>
      </body>
    </html>
  );
}
